services:
  - type: web
    name: careofjobs-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://saikrishnaennam_admin:KfJiPbXd035pJqBN@cluster0.q4xfibj.mongodb.net/jobportal?retryWrites=true&w=majority
      - key: API_ORIGIN
        value: https://careofjobs.github.io
      - key: API_KEY
        value: dev-secret-key-2024
